spring.datasource.url=jdbc:postgresql://db.pkufttndfpwzsyqepqjt.supabase.co:5432/postgres?user=postgres&password=AgpE)Fb=9kcPcQ@
spring.datasource.username=postgres
spring.datasource.password=AgpE)Fb=9kcPcQ@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true